spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fpapp
    username: ${DB_USER}
    password: ${DB_PASS_WORD}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    format:
      date: yyyy-MM-dd
  web:
    cors:
      allowed-origins: http://localhost:5173
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: app.fp.domain
  flyway:
    enabled: true
    locations: classpath:db/migration
flyway:
  url: jdbc:postgresql://localhost:5432/fpapp
  user: ${DB_USER}
  password: ${DB_PASS_WORD}
  clean-disabled: false
server:
  servlet:
    context-path: ""
